<b>La nouvelle session commence! Les Tempêtes de neige aussi!</b><br>
Assurez vous de vérifier si votre cours à lieu. un logo spécial vous indiquera s'il y a cours ou non!<br>
<br>
<b>Québec Natation dans les médias!</b><br>
<a href="http://tva.canoe.ca/emissions/salutbonjourwe/pleinair/96756.html" target="_BLANK"><font color="black">Visionnez la capsule qui a passé sur les ondes de TVA</font></a>